<?php
/**
 * PaymentOptionsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace pachirapay;

use \pachirapay\Configuration;
use \pachirapay\ApiException;
use \pachirapay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentOptionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentOptionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1PaymentOptionsMerchantsByMerchantIdSitesByMerchantSiteIdGet
     *
     * Gets payment options.
     *
     */
    public function testV1PaymentOptionsMerchantsByMerchantIdSitesByMerchantSiteIdGet()
    {
    }

    /**
     * Test case for v1PaymentOptionsPost
     *
     * Gets payment options for a context.
     *
     */
    public function testV1PaymentOptionsPost()
    {
    }

    /**
     * Test case for v1PaymentOptionsValidateEligibilityPost
     *
     * Validates eligibility.
     *
     */
    public function testV1PaymentOptionsValidateEligibilityPost()
    {
    }
}
