<?php
/**
 * Card3DsAuthorizeWithAuthDataRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace pachirapay;

use PHPUnit\Framework\TestCase;

/**
 * Card3DsAuthorizeWithAuthDataRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Authorization / payment request with authentication data
 * @package     pachirapay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Card3DsAuthorizeWithAuthDataRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Card3DsAuthorizeWithAuthDataRequest"
     */
    public function testCard3DsAuthorizeWithAuthDataRequest()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "authentication_data"
     */
    public function testPropertyAuthenticationData()
    {
    }

    /**
     * Test attribute "validation_mode"
     */
    public function testPropertyValidationMode()
    {
    }

    /**
     * Test attribute "notification_url"
     */
    public function testPropertyNotificationUrl()
    {
    }
}
