<?php
/**
 * Card3DsValidateAuthenticationResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CpaymentConnector
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace CpaymentConnector;

use PHPUnit\Framework\TestCase;

/**
 * Card3DsValidateAuthenticationResponseTest Class Doc Comment
 *
 * @category    Class
 * @description The card payment response
 * @package     CpaymentConnector
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Card3DsValidateAuthenticationResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Card3DsValidateAuthenticationResponse"
     */
    public function testCard3DsValidateAuthenticationResponse()
    {
    }

    /**
     * Test attribute "authentication_status"
     */
    public function testPropertyAuthenticationStatus()
    {
    }

    /**
     * Test attribute "liability_shift_status"
     */
    public function testPropertyLiabilityShiftStatus()
    {
    }

    /**
     * Test attribute "authentication_data"
     */
    public function testPropertyAuthenticationData()
    {
    }

    /**
     * Test attribute "response_message"
     */
    public function testPropertyResponseMessage()
    {
    }
}
