<?php
/**
 * PaymentSessionSubOrderResultTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace pachirapay;

use PHPUnit\Framework\TestCase;

/**
 * PaymentSessionSubOrderResultTest Class Doc Comment
 *
 * @category    Class
 * @description All payment operation data of the suborder
 * @package     pachirapay
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentSessionSubOrderResultTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentSessionSubOrderResult"
     */
    public function testPaymentSessionSubOrderResult()
    {
    }

    /**
     * Test attribute "order_ref"
     */
    public function testPropertyOrderRef()
    {
    }

    /**
     * Test attribute "payment_result_code"
     */
    public function testPropertyPaymentResultCode()
    {
    }

    /**
     * Test attribute "payment_result_code_message"
     */
    public function testPropertyPaymentResultCodeMessage()
    {
    }

    /**
     * Test attribute "payment_result_complementary_code"
     */
    public function testPropertyPaymentResultComplementaryCode()
    {
    }

    /**
     * Test attribute "payment_result_complementary_code_message"
     */
    public function testPropertyPaymentResultComplementaryCodeMessage()
    {
    }
}
