<?php
/**
 * Card3DsPaymentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace pachirapay;

use \pachirapay\Configuration;
use \pachirapay\ApiException;
use \pachirapay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * Card3DsPaymentApiTest Class Doc Comment
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Card3DsPaymentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1PaymentsCard3dsPaymentAuthenticationPost
     *
     * Validate authentication..
     *
     */
    public function testV1PaymentsCard3dsPaymentAuthenticationPost()
    {
    }

    /**
     * Test case for v1PaymentsCard3dsPaymentPost
     *
     * Check enrollment.
     *
     */
    public function testV1PaymentsCard3dsPaymentPost()
    {
    }

    /**
     * Test case for v1PaymentsCard3dsPaymentPut
     *
     * Validate authentication AND authorize / payment.
     *
     */
    public function testV1PaymentsCard3dsPaymentPut()
    {
    }

    /**
     * Test case for v1PaymentsCard3dsPaymentWithAuthenticationDataPost
     *
     * Authorization / payment -with- authentication data.
     *
     */
    public function testV1PaymentsCard3dsPaymentWithAuthenticationDataPost()
    {
    }
}
