<?php
/**
 * PaymentSessionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace pachirapay;

use \pachirapay\Configuration;
use \pachirapay\ApiException;
use \pachirapay\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentSessionApiTest Class Doc Comment
 *
 * @category Class
 * @package  pachirapay
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentSessionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for v1PaymentSessionsByPaymentSessionIdPaymentResultGet
     *
     * Gets the payment result from its session id..
     *
     */
    public function testV1PaymentSessionsByPaymentSessionIdPaymentResultGet()
    {
    }

    /**
     * Test case for v1PaymentSessionsPost
     *
     * Creates a payment session..
     *
     */
    public function testV1PaymentSessionsPost()
    {
    }
}
